
-- @RECOLABS Database Schema
-- Last Updated: 2026-04-29

-- 1. Enable UUID Extension (Optional, using serial IDs based on current code)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Books Table
CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'GENERAL',
    unique_code TEXT UNIQUE, -- Legacy 4 digit code (existing books only)
    isbn TEXT, -- International Standard Book Number
    author TEXT,
    publisher TEXT,
    published TEXT,
    pages INT,
    binding TEXT,
    status TEXT NOT NULL CHECK (status IN ('AVAILABLE', 'ISSUED')) DEFAULT 'AVAILABLE'
);

-- 3. Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id TEXT NOT NULL UNIQUE, -- The ID the student uses to login/scan
    name TEXT NOT NULL,
    email TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT REFERENCES books(id) ON DELETE CASCADE NOT NULL,
    student_internal_id BIGINT REFERENCES students(id) ON DELETE CASCADE NOT NULL,
    issue_date TIMESTAMPTZ DEFAULT NOW(),
    return_date TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED')) DEFAULT 'ACTIVE'
);

-- 5. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_books_code ON books(unique_code);
CREATE INDEX IF NOT EXISTS idx_books_isbn ON books(isbn);
CREATE INDEX IF NOT EXISTS idx_students_external_id ON students(student_id);
CREATE INDEX IF NOT EXISTS idx_transactions_active ON transactions(status) WHERE status = 'ACTIVE';

-- 6. Row Level Security (RLS) policies
-- Note: Admin access is managed via Supabase Auth.
-- Ensure you have an admin user in auth.users and policies to restrict access if needed.

-- Default Deny
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Allow public read of books for the Kiosk
CREATE POLICY "Allow public read of books" ON books FOR SELECT USING (true);

-- Allow kiosk to flip book status when issuing / returning
CREATE POLICY "Allow public book status update" ON books FOR UPDATE USING (true) WITH CHECK (status IN ('AVAILABLE', 'ISSUED'));

-- Allow public student registration (insert)
CREATE POLICY "Allow public student signup" ON students FOR INSERT WITH CHECK (true);

-- Allow public checking if student exists
CREATE POLICY "Allow public lookup of students" ON students FOR SELECT USING (true);

-- Allow public creation of transactions (Issue Book)
CREATE POLICY "Allow public book issuance" ON transactions FOR INSERT WITH CHECK (true);

-- Allow public lookup of transactions (Return Kiosk flow)
CREATE POLICY "Allow public read of transactions" ON transactions FOR SELECT USING (true);

-- Allow public updates to transactions (Return Book)
CREATE POLICY "Allow public book return" ON transactions FOR UPDATE USING (status = 'ACTIVE') WITH CHECK (status IN ('ACTIVE', 'RETURNED'));

-- Admin Override Policies (Assuming admin is authenticated)
CREATE POLICY "Admins full access on books" ON books FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full access on students" ON students FOR ALL TO authenticated USING (true);
CREATE POLICY "Admins full access on transactions" ON transactions FOR ALL TO authenticated USING (true);
